"""
PaintPro Inventory Management System
=====================================
Inventory Page  |  pages/inventory.py

Manage paint products: view as grid/table, add, edit, delete.
"""

import streamlit as st
import pandas as pd
from utils.auth import require_auth, get_current_user
from utils.formatting import slugify, get_stock_badge_html
from utils.validators import validate_required, validate_price, validate_stock, validate_hex_color, validate_sku
from models.product import ProductModel
from database.connection import execute_query
from components.color_preview import render_product_color_card
from utils.barcode_gen import generate_qr_code, generate_barcode
from config.constants import PAINT_TYPES, PAINT_FINISHES, PACK_SIZES, STORAGE_LOCATIONS

# ─── Load Reference Data ──────────────────────────────────────────────────────

@st.cache_data(ttl=60)
def _load_categories() -> dict:
    rows = execute_query("SELECT id, name FROM categories WHERE is_active=1 ORDER BY name")
    return {r["name"]: r["id"] for r in rows}

@st.cache_data(ttl=60)
def _load_brands() -> dict:
    rows = execute_query("SELECT id, name FROM brands WHERE is_active=1 ORDER BY name")
    return {r["name"]: r["id"] for r in rows}

@st.cache_data(ttl=60)
def _load_suppliers() -> dict:
    rows = execute_query("SELECT id, name FROM suppliers WHERE is_active=1 ORDER BY name")
    return {r["name"]: r["id"] for r in rows}

# ─── Modal Dialogs ────────────────────────────────────────────────────────────

@st.dialog("Print Tags / Labels", width="small")
def _tags_dialog(sku: str, name: str):
    st.markdown(f"### 🏷️ Labels for **{sku}**")
    st.caption(f"{name}")
    
    t1, t2 = st.tabs(["QR Code", "Barcode (Code128)"])
    with t1:
        st.markdown("<div style='text-align:center;'>", unsafe_allow_html=True)
        st.image(generate_qr_code(sku), width=200)
        st.markdown(f"<b>{sku}</b>", unsafe_allow_html=True)
        st.markdown("</div>", unsafe_allow_html=True)
        
    with t2:
        st.markdown("<div style='text-align:center; padding-top:20px;'>", unsafe_allow_html=True)
        # Barcodes generated by python-barcode with ImageWriter already include text by default
        st.image(generate_barcode(sku), use_container_width=True)
        st.markdown("</div>", unsafe_allow_html=True)
    
    st.info("Right-click an image to save or print it for bin labeling.")

@st.dialog("Delete Product")
def _delete_dialog(product_id: int, product_name: str):
    st.warning(f"Are you sure you want to delete **{product_name}**?")
    st.markdown("This will soft-delete the product. It won't appear in new transactions but historical data will be preserved.")
    
    col1, col2 = st.columns(2)
    if col1.button("Cancel", use_container_width=True):
        st.rerun()
    if col2.button("Yes, Delete", type="primary", use_container_width=True):
        ok, msg = ProductModel.delete(product_id, get_current_user()["id"])
        if ok:
            st.success("Product deleted successfully!")
            st.session_state["_refresh_trigger"] = True
            st.rerun()
        else:
            st.error(f"Failed to delete: {msg}")

@st.dialog("Product Form", width="large")
def _product_form_dialog(product_id: int = None):
    categories = _load_categories()
    brands = _load_brands()
    suppliers = _load_suppliers()
    
    is_edit = product_id is not None
    prod = {}
    if is_edit:
        prod = ProductModel.get_by_id(product_id)
        if not prod:
            st.error("Product not found.")
            return

    st.markdown(f"### {'Edit' if is_edit else 'Add'} Paint Product")
    
    with st.form("product_form"):
        # Basic Info
        st.markdown("##### Basic Information")
        col1, col2 = st.columns(2)
        with col1:
            name = st.text_input("Product Name *", value=prod.get("name", ""))
            sku = st.text_input("SKU *", value=prod.get("sku", ""))
        with col2:
            cat_name = next((k for k,v in categories.items() if v == prod.get("category_id")), None)
            sel_cat = st.selectbox("Category", options=["Select"] + list(categories.keys()), index=(list(categories.keys()).index(cat_name) + 1) if cat_name else 0)
            
            brand_name = next((k for k,v in brands.items() if v == prod.get("brand_id")), None)
            sel_brand = st.selectbox("Brand", options=["Select"] + list(brands.keys()), index=(list(brands.keys()).index(brand_name) + 1) if brand_name else 0)

        # Paint Specifics
        st.markdown("##### Paint Attributes")
        c1, c2, c3, c4 = st.columns(4)
        with c1:
            p_type = st.selectbox("Type", options=["Select"] + PAINT_TYPES, index=(PAINT_TYPES.index(prod.get("paint_type")) + 1) if prod.get("paint_type") in PAINT_TYPES else 0)
        with c2:
            p_finish = st.selectbox("Finish", options=["Select"] + PAINT_FINISHES, index=(PAINT_FINISHES.index(prod.get("finish")) + 1) if prod.get("finish") in PAINT_FINISHES else 0)
        with c3:
            p_size = st.selectbox("Pack Size", options=["Select"] + PACK_SIZES, index=(PACK_SIZES.index(prod.get("pack_size")) + 1) if prod.get("pack_size") in PACK_SIZES else 0)
        with c4:
            color_name = st.text_input("Color Name", value=prod.get("color_name", ""))
            
        c5, c6 = st.columns(2)
        with c5:
            hex_color = st.text_input("HEX Color Code", value=prod.get("color_hex", ""), placeholder="#FFFFFF")
            st.caption("Enter hex to show color preview.")
        with c6:
            rgb_color = st.text_input("RGB Color", value=prod.get("color_rgb", ""), placeholder="255,255,255")

        # Pricing & Stock
        st.markdown("##### Pricing & Stock")
        p1, p2, p3 = st.columns(3)
        with p1:
            cost = st.number_input("Cost Price (₹) *", value=float(prod.get("cost_price", 0.0)), min_value=0.0)
        with p2:
            sell = st.number_input("Selling Price (₹) *", value=float(prod.get("selling_price", 0.0)), min_value=0.0)
        with p3:
            gst = st.selectbox("GST %", options=[0, 5, 12, 18, 28], index=[0, 5, 12, 18, 28].index(int(prod.get("gst_percentage", 18))))

        s1, s2, s3 = st.columns(3)
        with s1:
            curr_stock = st.number_input("Current Stock", value=float(prod.get("current_stock", 0.0)), min_value=0.0, disabled=is_edit)
            if is_edit: st.caption("Use Stock Mgmt to adjust.")
        with s2:
            min_stock = st.number_input("Min Stock (Alert)", value=float(prod.get("minimum_stock", 5.0)), min_value=0.0)
        with s3:
            location = st.selectbox("Storage Location", options=["Select"] + STORAGE_LOCATIONS, index=(STORAGE_LOCATIONS.index(prod.get("storage_location")) + 1) if prod.get("storage_location") in STORAGE_LOCATIONS else 0)

        submitted = st.form_submit_button("Save Product", type="primary", use_container_width=True)
        
        if submitted:
            errors = []
            ok, msg = validate_required(name, "Name"); not ok and errors.append(msg)
            ok, msg = validate_sku(sku); not ok and errors.append(msg)
            ok, msg = validate_price(cost, "Cost Price"); not ok and errors.append(msg)
            ok, msg = validate_price(sell, "Selling Price"); not ok and errors.append(msg)
            if hex_color:
                ok, msg = validate_hex_color(hex_color); not ok and errors.append(msg)

            if errors:
                for err in errors: st.error(err)
            else:
                data = {
                    "name": name,
                    "sku": sku,
                    "slug": slugify(sku + "-" + name),
                    "category_id": categories.get(sel_cat) if sel_cat != "Select" else None,
                    "brand_id": brands.get(sel_brand) if sel_brand != "Select" else None,
                    "paint_type": p_type if p_type != "Select" else None,
                    "finish": p_finish if p_finish != "Select" else None,
                    "pack_size": p_size if p_size != "Select" else None,
                    "color_name": color_name,
                    "color_hex": hex_color if hex_color else None,
                    "color_rgb": rgb_color if rgb_color else None,
                    "cost_price": cost,
                    "selling_price": sell,
                    "gst_percentage": gst,
                    "minimum_stock": min_stock,
                    "storage_location": location if location != "Select" else None,
                }
                
                uid = get_current_user()["id"]
                if is_edit:
                    ok, msg = ProductModel.update(product_id, data, uid)
                else:
                    data["current_stock"] = curr_stock
                    ok, msg = ProductModel.create(data, uid)
                    
                if ok:
                    st.success("Saved successfully!")
                    st.session_state["_refresh_trigger"] = True
                    st.rerun()
                else:
                    st.error(f"Error: {msg}")

# ─── Main Render ──────────────────────────────────────────────────────────────

def render():
    require_auth()

    # Navbar
    st.markdown(
        """
<div class="paintpro-navbar">
    <div class="navbar-page-title">Paint Inventory</div>
</div>
""",
        unsafe_allow_html=True
    )
    
    st.markdown("<div style='padding: 24px;'>", unsafe_allow_html=True)
    
    # ─── Toolbar ──────────────────────────────────────────────────────────────
    t_col1, t_col2, t_col3, t_col4 = st.columns([2, 1, 1, 1], gap="medium")
    with t_col1:
        search = st.text_input("🔍 Search Products", placeholder="Search by name, SKU, or color...", label_visibility="collapsed")
    with t_col2:
        view_mode = st.selectbox("View Mode", options=["Grid View (Color Cards)", "Table View"], label_visibility="collapsed")
    with t_col3:
        pass # Spacer
    with t_col4:
        if st.button("➕ Add Product", use_container_width=True, type="primary"):
            _product_form_dialog()

    st.markdown("<hr>", unsafe_allow_html=True)

    # ─── Fetch Data ───────────────────────────────────────────────────────────
    products = ProductModel.get_all(search_query=search)
    
    if not products:
        st.markdown(
            """
<div class="empty-state">
  <div class="empty-state-icon">📦</div>
  <div class="empty-state-title">No products found</div>
  <div class="empty-state-desc">Try adjusting your search or add a new product.</div>
</div>
""", 
            unsafe_allow_html=True
        )
        return

    # ─── Render View ──────────────────────────────────────────────────────────
    if "Grid" in view_mode:
        # Premium Feature 2: Paint Color Preview Grid
        cols_per_row = 4
        for i in range(0, len(products), cols_per_row):
            cols = st.columns(cols_per_row)
            for j in range(cols_per_row):
                if i + j < len(products):
                    p = products[i + j]
                    with cols[j]:
                        render_product_color_card(p)
                        
                        # Action Buttons under card
                        ac1, ac2, ac3 = st.columns(3)
                        with ac1:
                            if st.button("✏️ Edit", key=f"edit_{p['id']}", use_container_width=True):
                                _product_form_dialog(p['id'])
                        with ac2:
                            if st.button("🏷️ Tags", key=f"tag_{p['id']}", use_container_width=True):
                                _tags_dialog(p['sku'], p['name'])
                        with ac3:
                            if st.button("🗑️ Del", key=f"del_{p['id']}", use_container_width=True):
                                _delete_dialog(p['id'], p['name'])
    else:
        # Table View
        rows_html = ""
        for p in products:
            status_badge = get_stock_badge_html(p['current_stock'], p['minimum_stock'])
            color_dot = f'<span style="display:inline-block;width:12px;height:12px;border-radius:50%;background-color:{p["color_hex"] or "#ccc"};border:1px solid #000;margin-right:6px;"></span>'
            
            rows_html += f"""
<tr>
    <td><b>{p['sku']}</b></td>
    <td>{color_dot}{p['name']}</td>
    <td>{p['brand_name'] or '-'}</td>
    <td>{p['category_name'] or '-'}</td>
    <td style="text-align:right;">₹{float(p['selling_price']):,.2f}</td>
    <td style="text-align:right;"><b>{float(p['current_stock']):g}</b></td>
    <td>{status_badge}</td>
    <td>
        <!-- Streamlit buttons are tricky inside pure HTML table. We'll use a dataframe instead for interactivity if we want buttons, OR we can just use st.data_editor. -->
        <span style="color:var(--text-muted);font-size:0.75rem;">Switch to Grid view to edit</span>
    </td>
</tr>
"""
            
        st.markdown(
            f"""
<div class="paintpro-table-wrapper">
    <table class="paintpro-table">
        <thead>
            <tr>
                <th>SKU</th>
                <th>Product Name</th>
                <th>Brand</th>
                <th>Category</th>
                <th style="text-align:right;">Price</th>
                <th style="text-align:right;">Stock</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>{rows_html}</tbody>
    </table>
</div>
""", 
            unsafe_allow_html=True
        )

        st.markdown("#### Quick Actions")
        cols_per_row = 4
        for i in range(0, len(products), cols_per_row):
            cols = st.columns(cols_per_row)
            for j in range(cols_per_row):
                if i + j < len(products):
                    p = products[i + j]
                    with cols[j]:
                        st.markdown(f"<small>**{p['sku']}**</small><br>**{p['name']}**", unsafe_allow_html=True)
                        ac1, ac2, ac3 = st.columns(3)
                        with ac1:
                            if st.button("✏️ Edit", key=f"t_edit_{p['id']}", use_container_width=True):
                                _product_form_dialog(p['id'])
                        with ac2:
                            if st.button("🏷️ Tags", key=f"t_tag_{p['id']}", use_container_width=True):
                                _tags_dialog(p['sku'], p['name'])
                        with ac3:
                            if st.button("🗑️ Del", key=f"t_del_{p['id']}", use_container_width=True):
                                _delete_dialog(p['id'], p['name'])
                        st.markdown("<hr style='margin:10px 0;'>", unsafe_allow_html=True)

    st.markdown("</div>", unsafe_allow_html=True)
